### ISSUE TITLE
Placing images above 2 colums

### ISSUE THREAD

**Issue by Allmedialab** [ThemeMountain/pine#23]
Hi,
How do I place an image above two columns in a way they show image, text, image, text on a mobile phone?    https://thememountain.github.io/documentation/pine/components/feature-columns.html
Regards,
David

**Comment by cossssmin** [comment]
Hi,

Not sure I understand, are you perhaps trying to [reverse stack columns on mobile](https://thememountain.github.io/documentation/pine/utilities/reverse-stack.html)?

**Comment by Allmedialab** [comment]
Hi,
I see what you mean!
Regards & Thanks,
David

**Comment by cossssmin** [comment]
Sure thing :)

If that answers your question, please close the issue.

Cheers, 
Cosmin
