### ISSUE TITLE
Add email preview feature

### ISSUE THREAD

**Issue by udf2457** [ThemeMountain/pine#24]
I've been looking for a new email framework.  Pine looks interesting, but also HEML has one or two extra interesting features such as `Preview` (https://github.com/SparkPost/heml/blob/master/packages/heml-elements/src/Preview.js) which is intended to show one-liner previews in Apple Mail, Gmail etc (https://heml.io/docs/getting-started/guide).  More generic info on preview here: https://litmus.com/blog/the-ultimate-guide-to-preview-text-support

Any plans to add this sort of thing to `pine` or will it be left to users to implement ?

**Comment by cossssmin** [comment]
The base layout in Pine already comes with a preheader 'component':

https://github.com/ThemeMountain/pine/blob/93202108adec32862c3e0e83c6793abe05ac752d/layouts/boilerplate.html#L148

---

Pine is more like a boilerplate. It doesn't have a build system and, unlike HEML or MJML, you need to write your own HTML - there is no custom markup that magically expands into email-optimized HTML.

To answer your question, there are no plans on adding anything like that. 

Pine (and [Acorn](https://github.com/ThemeMountain/acorn)) will remain as boilerplates. For a framework with an actual build system, you can try out [Maizzle](https://maizzle.com) - though it still requires you write your own HTML. A Node.js-only version of Maizzle is coming soon.

**Comment by udf2457** [comment]
Thanks for the clarification.  Much appreciated !
