### ISSUE TITLE
Docs unclear vs boilerplate ?

### ISSUE THREAD

**Issue by udf2457** [ThemeMountain/pine#25]
The docs (https://docs.thememountain.com/pine/grid/) state:

> we can take advantage of that and use width="100%" on them.

and provide associated code:

`<table cellpadding="0" cellspacing="0" role="presentation" width="100%">`

and yet your `boilerplate.html` seems to suggest a fixed width:

`<table class="container" cellpadding="0" cellspacing="0" role="presentation" width="700">`

What is the "correct" way to do things ?

**Comment by cossssmin** [comment]
That is talking about grid Rows. What you pasted from the boilerplate is the Container, which sets a fixed width on the table that wraps the rows. 

So you can change the container width in a single place (the boilerplate) and have all your rows respect that.

**Comment by cossssmin** [comment]
Start with the layout overview docs, then move on to the grid :)

https://docs.thememountain.com/pine/layout/#container
