### ISSUE TITLE
Pine template showing mobile view on iPad Pro

### ISSUE THREAD

**Issue by carmig1611** [ThemeMountain/pine#27]
I'm having issues when testing a Pine template, it is showing the mobile view on the iPad Pro whereas it should be showing the desktop view. I have looked at adding media queries for the iPad, but all to no avail. Today I tried taking some of the code from the Kant template that you have on https://kant.thememountain.com/email/index.html, but even this still shows up as mobile view on the iPad Pro. I have run some Litmus tests and have also device tested. I have added two screenshots, one of the iPad mini, which is displaying correctly and the other is the iPad Pro, which is not displaying correctly.
Many thanks
Gary Carmichael
![Screenshot_ipad_mini](https://user-images.githubusercontent.com/57444797/68301510-01982a80-0098-11ea-94ea-773c48d709f0.png)
![Screenshot_ipad_pro](https://user-images.githubusercontent.com/57444797/68301511-0230c100-0098-11ea-9ee6-f8b75478ef3f.png)

**Comment by carmig1611** [comment]
I have found a temporary fix by reducing the width of one of the media queries from 699px to 669px (that was the largest I could go without the iPad Pro showing the mobile view)
@media only screen and (max-width: 669px)

**Comment by cossssmin** [comment]
Sorry for the late response, was away for a couple of days. Yes, I was also going to suggest simply changing the media query 👍

iPads (including Pro), even if they're a mobile device, have such a big screen that it can easily fall into the 'laptops' category, so it would be normal to see the desktop layout on it.

**Comment by carmig1611** [comment]
Cosmin

Thank you. I was a bit reluctant to change any of the styles, whence the request. As you say the simplest solution was to change the break point.

Many thanks
Gary Carmichael
